services:
  onion_service:
    build: ./requirements/onion 
    container_name: onion_container
    volumes:
      - tor_metadata:/var/lib/tor/hidden_service
    secrets:
      - ssh_password
      - ssh_user
    restart: always
    expose:
      - 4242:4242

volumes:
  tor_metadata:

secrets:
  ssh_password:
    file: ./secrets/ssh_password.txt
  ssh_user:
    file: ./secrets/ssh_user.txt